id: 35c11bb29a9347d5aed968ed1f5f4b05
initial_creation_type: ocr
source_metadata:
  volumes:
    413e8b2be40a43fe88c6228332da8f6c:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
